### ISSUE TITLE
Cannot run on Android 6 API level 23

### ISSUE THREAD

**Issue by sonhvse61570** [ByneappLLC/flutter_config#29]
This is my flutter version:
![image](https://user-images.githubusercontent.com/12763652/106695304-e276a880-660c-11eb-9314-14adfafb8fbf.png)

I tried to run with android 6, but flutter throw exception: 
![image](https://user-images.githubusercontent.com/12763652/106695149-97f52c00-660c-11eb-8f08-1f266e0636e3.png)

Please give us the version that your lib support.
Thanks

**Comment by nehamallama** [comment]
RUN AWAY! They dont update anything or respond to any open issues. Use this dep instead https://pub.dev/packages/flutter_dotenv

**Comment by edTheGuy00** [comment]
You'll get a `MissingPluginException` If you are using hot restart or hot reload and add Native Plugins. make sure you stop the running application and run `flutter run` again. Would also recommend running `flutter clean` . 

I'm going to close this issue since I assume you are following @nehamallama suggestion
