### ISSUE TITLE
i cant execute signingReport

### ISSUE THREAD

**Issue by abehbatre** [ByneappLLC/flutter_config#50]
halo i use flutter_config and make 3 flavor .
and now i need to execute `./gradlew signingReport` . and it show error 

```
➜  android git:(development) ✗ ./gradlew signingReport

> Configure project :app
Reading env from: .env
**************************
*** Missing .env file ****
**************************

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Aditya.Pratama/StudioProjects/blabla-project/android/app/build.gradle' line: 63

* What went wrong:
A problem occurred evaluating project ':app'.
> Parameter specified as non-null is null: method com.android.build.gradle.internal.dsl.BaseFlavor.resValue, parameter value

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by edTheGuy00** [comment]
Hello, please follow the [Android setup guide](https://github.com/ByneappLLC/flutter_config/blob/master/doc/ANDROID.md) . `signingReport ` should work as long as everything is setup correctly. The issue you are seeing is because the [gradle script](https://github.com/ByneappLLC/flutter_config/blob/ed3a01f687526a58bed79b804c38c3481ae34108/android/dotenv.gradle#L53) is unable to find the `.env` files.

**Comment by abehbatre** [comment]
@edTheGuy00 thanks
