### ISSUE TITLE
Possibility to use more that one .env file

### ISSUE THREAD

**Issue by dayveedaniel** [ByneappLLC/flutter_config#56]
The plugin only read ".env", is there a possibility to define the file to read from , for example .env.dev , .env.prod

_Reading env from: .env_

**Comment by edTheGuy00** [comment]
You can setup as many as you want along with app flavors. Instructions are detailed in: 

[Android - Different Environments](https://github.com/ByneappLLC/flutter_config/blob/master/doc/ANDROID.md#different-environments)

[iOS - Different Environments](https://github.com/ByneappLLC/flutter_config/blob/master/doc/IOS.md#different-environments)

**Comment by gwijaya94** [comment]
Hi @edTheGuy00, I use multiple environment (dev, beta, prod),
and ofc have multiple .env too.
I define all of the build variants into this:
```
project.ext.envConfigFiles = [
    devDebug: ".env.dev",
    devRelease: ".env.dev",
    betaDebug: ".env.beta",
    betaRelease: ".env.beta",
    prodDebug: ".env.prod",
    prodRelease: ".env.prod",
]
```

then I run command ``flutter run --flavor=beta``,  I noticed it throws error because .env file not found or have empty content.
But succeed when I copied .env.beta content to .env files.
Does it not automatically use .env.beta when we run the command ? even though flutter recognize it when running into assembleBetaDebug.
```
> flutter run --flavor=beta
Launching lib\main.dart on MI 9 in debug mode...
Reading env from: .env
Running Gradle task 'assembleBetaDebug'...     
``` 

Or we should manually set script to copy .env.beta into .env ?

I remember in React Native with the same code, I run only ``yarn run android --mode=betaDebug`` and it automatically use .env.beta
Thankyou.
